<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>HDFC_Playwrite_AI</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>HDFC_Playwrite_AI</name>
	<description>Test Automation project for HDFC With AI</description>
	<url />
	<licenses>
		<license />
	</licenses>
	<developers>
		<developer />
	</developers>
	<scm>
		<connection />
		<developerConnection />
		<tag />
		<url />
	</scm>
	<properties>
		<java.version>17</java.version>
		<playwright.version>1.44.0</playwright.version>
		<cucumber-java.version>7.18.0</cucumber-java.version>
		<cucumber-spring.version>7.18.0</cucumber-spring.version>
		<cucumber-spring.version>7.18.0</cucumber-spring.version>
		<cucumber-junit-platform-engine.version>7.18.0</cucumber-junit-platform-engine.version>
		<allure-cucumber7-jvm.version>2.27.0</allure-cucumber7-jvm.version>
		<testng.version>7.12.2</testng.version>
		<!--
		<java.version>21</java.version>
		<selenium.version>4.28.1</selenium.version>
		<webdrivermanager.version>5.9.2</webdrivermanager.version>
		<testng.version>7.10.2</testng.version>
		<cucumber.version>7.20.1</cucumber.version>
		<faker.verison>1.0.2</faker.verison>
		<maven.surefire.plugin>3.0.0-M1</maven.surefire.plugin>
		-->

	</properties>
	<dependencies>
		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>playwright</artifactId>
			<version>${playwright.version}</version>
		</dependency>
		
		<!-- testng users only -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- Cucumber Spring Integration -->
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>${cucumber-java.version}</version>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-spring</artifactId>
        <version>${cucumber-spring.version}</version>
    </dependency>
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-junit-platform-engine</artifactId>
        <version>${cucumber-junit-platform-engine.version}</version>
    </dependency>
    <!-- Allure Cucumber Report -->
    <dependency>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-cucumber7-jvm</artifactId>
        <version>${allure-cucumber7-jvm.version}</version>
    </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
